### ISSUE TITLE
unicodeDedodeError

### ISSUE THREAD

**Issue by philoo9999** [krmaxwell/maltrieve#178]
Hi

I installed maltrieve many times before. no problem
on a new machine, I have the following error : 

pip install -e . 

.....
.....
Downloading/unpacking pytest (from maltrieve==0.7)
  Downloading pytest-2.8.0-py2.py3-none-any.whl (147kB): 147kB downloaded
Downloading/unpacking pytest-cov (from maltrieve==0.7)
  Downloading pytest_cov-2.1.0-py2.py3-none-any.whl
Downloading/unpacking coveralls (from maltrieve==0.7)
  Downloading coveralls-1.0-py2.py3-none-any.whl
Downloading/unpacking LinkChecker (from maltrieve==0.7)
  Downloading LinkChecker-9.3.tar.gz (719kB): 719kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
    untar_file(filename, location)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 574, in untar_file
    path = os.path.join(location, fn)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 20: ordinal not in range(128)

Storing debug log for failure in /root/.pip/pip.log

any idea ? 

kind regards

**Comment by johnfellers** [comment]
i had the same issue...

i fixed this by running
$ sudo pip install LinkChecker==9.3

then rerun sudo pip install -r requirements.txt
