### ISSUE TITLE
Problem with new filemagic?

### ISSUE THREAD

**Issue by krmaxwell** [krmaxwell/maltrieve#62]
```
Traceback (most recent call last):
  File "maltrieve.py", line 333, in <module>
    main()
  File "maltrieve.py", line 308, in main
    md5 = save_malware(each, cfg['dumpdir'], ignore_list)
  File "maltrieve.py", line 104, in save_malware
    mime_type = magic.from_buffer(data, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'
```

unsure whether I have the wrong module or some other problem

**Comment by krmaxwell** [comment]
wrong module, that's all
