### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by adimenia** [krmaxwell/maltrieve#65]
is there a reason i keep getting these exceptions when running the tool.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/bin/maltrieve.py", line 52, in get_malware
    mal = get_URL(url)
  File "/usr/local/maltrieve/malutil.py", line 17, in get_URL
    response.getcode())
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by krmaxwell** [comment]
Fixed by #93 and #91
