### ISSUE TITLE
Output Shows Not JSON Serialized After Running.

### ISSUE THREAD

**Issue by dray0n** [krmaxwell/maltrieve#89]
> Processing source URLs
> Completed source processing
> Traceback (most recent call last):
> File "./maltrieve.py", line 349, in <module> main()
> File "./maltrieve.py", line 340, in main json.dump(past_urls, urlfile)
> File "/usr/lib/python2.7/json/__init__.py", line 189, in dump for chunk in iterable:
> File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode o = _default(o)
> File "/usr/lib/python2.7/json/encoder.py", line 184, in default raise TypeError(repr(o) + " is not JSON serializable")

Excuse any typos... I was unable to copy/paste from its source.

**Comment by dray0n** [comment]
> TypeError: set([u'http://website.com/blah.exe', continued array of urls]) is not JSON serializable

**Comment by dray0n** [comment]
Verified -- Maltrieve is working as intended. Thanks Kyle!
