### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by c0den** [krmaxwell/maltrieve#90]
-> % Traceback (most recent call last):
  File "/opt/maltrieve/maltrieve.py", line 349, in <module>
    main()
  File "/opt/maltrieve/maltrieve.py", line 294, in main
    past_urls = json.load(urlfile)
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This happens sometimes when maltrieve runs. The only way only way I can get maltrieve to run again is to delete urls.json

**Comment by krmaxwell** [comment]
Before you delete the file, how big is it?

**Comment by c0den** [comment]
0 bytes

**Comment by c0den** [comment]
This could be a result of the following bug "Output Shows Not JSON Serialized After Running"..this has not been confirmed but I remember seeing a similar error on the previous execution of maltrieve before the execution that yielded the bug I reported.
